<?php

use App\Models\Voter;
use App\Models\Employee;
use Illuminate\Database\Seeder;
use App\Models\Officer; // Adjust the namespace based on your model location

class EmployeeSeeder extends Seeder
{
    public function run()
    {
        $voters = [
            [
                'full_name' => 'মোহাম্মদ আজিজুল ইসলাম',
                'full_name_eng' => 'Mohammad Azizul Islam',
                'pin' => '19753523207124030',
                'contact_no' => '01820531300',
                'email' => 'aziz_deo@yahoo.com',
                'designation_bng' => 'আঞ্চলিক নির্বাচন কর্মকর্তা',
                'designation_status' => 'full',
                'office_location' => 'আঞ্চলিক নির্বাচন অফিস, কুমিল্লা (Field)',
            ],
            [
                'full_name' => 'মো: আলাউদ্দীন',
                'full_name_eng' => 'MD. ALAUDDIN',
                'pin' => '19785425401282549',
                'contact_no' => '01711337503',
                'email' => 'alauddinecs.gov.bd@gmail.com',
                'designation_bng' => 'আঞ্চলিক নির্বাচন কর্মকর্তা',
                'designation_status' => 'full',
                'office_location' => 'আঞ্চলিক নির্বাচন অফিস, সিলেট (Field)',
            ],
            [
                'full_name' => 'মোঃ ইউনুচ আলী',
                'full_name_eng' => 'Md. Yunus Ali',
                'pin' => '19786426001199001',
                'contact_no' => '01912530668',
                'email' => 'yunus1978ec@gmail.com',
                'designation_bng' => 'আঞ্চলিক নির্বাচন কর্মকর্তা',
                'designation_status' => 'full',
                'office_location' => 'আঞ্চলিক নির্বাচন অফিস, ঢাকা (Field)',
            ],
            [
                'full_name' => 'মোঃ ফরিদুল ইসলাম',
                'full_name_eng' => 'md. foridul islam',
                'pin' => '19791012785239000',
                'contact_no' => '01818604719',
                'email' => 'foridul.deo@gmail.com',
                'designation_bng' => 'আঞ্চলিক নির্বাচন কর্মকর্তা',
                'designation_status' => 'full',
                'office_location' => 'আঞ্চলিক নির্বাচন অফিস, বরিশাল (Field)',
            ],
            [
                'full_name' => 'মোহাম্মদ বেলায়েত হোসেন চৌধুরী',
                'full_name_eng' => 'Mohammad Balayet Hossain Chowdhury',
                'pin' => '19781910956209647',
                'contact_no' => '+8801716771855',
                'email' => 'balayet1978@yahoo.com',
                'designation_bng' => 'আঞ্চলিক নির্বাচন কর্মকর্তা',
                'designation_status' => 'full',
                'office_location' => 'আঞ্চলিক নির্বাচন অফিস, চট্টগ্রাম (Field)',
            ],
            [
                'full_name' => 'মোঃ আনিছুর রহমান',
                'full_name_eng' => 'Md. Anichur Rahaman',
                'pin' => '19742695041746579',
                'contact_no' => '+8801712197641',
                'email' => 'anis_06_06@yahoo.com',
                'designation_bng' => 'আঞ্চলিক নির্বাচন কর্মকর্তা',
                'designation_status' => 'cc',
                'office_location' => 'আঞ্চলিক নির্বাচন অফিস, রাজশাহী (Field)',
            ],
            [
                'full_name' => 'ফয়সল কাদের',
                'full_name_eng' => 'Faysal Kader',
                'pin' => '19804825407437851',
                'contact_no' => '01673640185',
                'email' => 'kaderfaysal9@gmail.com',
                'designation_bng' => 'আঞ্চলিক নির্বাচন কর্মকর্তা',
                'designation_status' => 'cc',
                'office_location' => 'আঞ্চলিক নির্বাচন অফিস, খুলনা (Field)',
            ],
            [
                'full_name' => 'মো: শাহিনুর ইসলাম প্রামানিক',
                'full_name_eng' => 'Md. Shahinur islam pramanik',
                'pin' => '19756426007161394',
                'contact_no' => '054151372, 01718242275', // Multiple numbers combined
                'email' => 'shahinurislam185@gmail.com',
                'designation_bng' => 'আঞ্চলিক নির্বাচন কর্মকর্তা',
                'designation_status' => 'cc',
                'office_location' => 'আঞ্চলিক নির্বাচন অফিস, ময়মনসিংহ (Field)',
            ],
            [
                'full_name' => 'মোঃ মাহবুব আলম শাহ্‌',
                'full_name_eng' => 'Md. Mahbub Alam Shah',
                'pin' => '19807712529420566',
                'contact_no' => '01716271898',
                'email' => 'mahabub9970@gmail.com',
                'designation_bng' => 'আঞ্চলিক নির্বাচন কর্মকর্তা',
                'designation_status' => 'cc',
                'office_location' => 'আঞ্চলিক নির্বাচন অফিস, ফরিদপুর (Field)',
            ],
            [
                'full_name' => 'মোঃ দেলোয়ার হোসেন',
                'full_name_eng' => 'Md. Delower Hossain',
                'pin' => '19752695435714492',
                'contact_no' => '01712971781, 0771-66835', // Multiple numbers combined
                'email' => 'delower_ecs_75@yahoo.com',
                'designation_bng' => 'আঞ্চলিক নির্বাচন কর্মকর্তা',
                'designation_status' => 'cc',
                'office_location' => 'আঞ্চলিক নির্বাচন অফিস, রংপুর (Field)',
            ],
            [
                'full_name' => 'মো: রোকুনুজ্জামান',
                'full_name_eng' => 'Md. Rokunuzzaman',
                'pin' => '19764423301402340',
                'contact_no' => '01715614098',
                'email' => 'rokunuzzaman705@gmail.com',
                'designation_bng' => 'সিনিয়র জেলা নির্বাচন অফিসার',
                'designation_status' => 'full',
                'office_location' => 'সিনিয়র জেলা নির্বাচন অফিস, বরিশাল (Field)',
            ],
            [
                'full_name' => 'তারেক আহমেমদ',
                'full_name_eng' => 'Tareq Ahammed',
                'pin' => '19781822309170748',
                'contact_no' => '01712047810',
                'email' => '-',
                'designation_bng' => 'সিনিয়র জেলা নির্বাচন অফিসার',
                'designation_status' => 'full',
                'office_location' => 'সিনিয়র জেলা নির্বাচন অফিস, ফরিদপুর (Field)',
            ],
            [
                'full_name' => 'মো: জিলহাজ উদ্দিন',
                'full_name_eng' => 'Md. Zelhas Uddin',
                'pin' => '19744915217295860',
                'contact_no' => '01715572038',
                'email' => 'zelhas12@gmail.com',
                'designation_bng' => 'সিনিয়র জেলা নির্বাচন অফিসার',
                'designation_status' => 'full',
                'office_location' => 'সিনিয়র জেলা নির্বাচন অফিস, দিনাজপুর (Field)',
            ],
            [
                'full_name' => 'মোঃ আবদুর রহিম',
                'full_name_eng' => 'MD. ABDUR RAHIM',
                'pin' => '19784910911560585',
                'contact_no' => '01761-868248',
                'email' => 'arahim1978@gmail.com',
                'designation_bng' => 'সিনিয়র জেলা নির্বাচন অফিসার',
                'designation_status' => 'full',
                'office_location' => 'সিনিয়র জেলা নির্বাচন অফিস, রংপুর (Field)',
            ],
            [
                'full_name' => 'আব্দুল্যাহ্ আল মোতাহসিম',
                'full_name_eng' => 'ABDULLAH-AL-MUTHASIM',
                'pin' => '19743910747343462',
                'contact_no' => '01712-415207',
                'email' => 'muthasim74@gmail.com',
                'designation_bng' => 'সিনিয়র জেলা নির্বাচন অফিসার',
                'designation_status' => 'full',
                'office_location' => 'সিনিয়র জেলা নির্বাচন অফিস, ময়মনসিংহ (Field)',
            ],
            [
                'full_name' => 'শেখ মুহাম্মদ হাবিবুর রহমান',
                'full_name_eng' => 'Shak Mohammed Habibur Rahaman',
                'pin' => '19795919455512375',
                'contact_no' => '01711239417',
                'email' => 'ueohabib@gmail.com',
                'designation_bng' => 'সিনিয়র জেলা নির্বাচন অফিসার',
                'designation_status' => 'full',
                'office_location' => 'সিনিয়র জেলা নির্বাচন অফিস, কুমিল্লা (Field)',
            ],
            [
                'full_name' => 'মুহাম্মদ মোশারফ হোসেন',
                'full_name_eng' => 'Muhammad Mosharaf Hossain',
                'pin' => '19778926706529200',
                'contact_no' => '01712393558',
                'email' => 'mmhossain2005@gmail.com',
                'designation_bng' => 'সিনিয়র জেলা নির্বাচন অফিসার',
                'designation_status' => 'full',
                'office_location' => 'জেলা নির্বাচন অফিস, নেত্রকোনা (Field)',
            ],
            [
                'full_name' => 'ওহিদুজ্জামান মুন্সী',
                'full_name_eng' => 'Ohiduzzaman Munshi',
                'pin' => '19795525702339984',
                'contact_no' => '01731-368095',
                'email' => 'ohiduzzaman60@gmail.com',
                'designation_bng' => 'সিনিয়র জেলা নির্বাচন অফিসার',
                'designation_status' => 'full',
                'office_location' => 'সিনিয়র জেলা নির্বাচন অফিস, পটুয়াখালী (Field)',
            ],
            [
                'full_name' => 'মোহাম্মদ মুঞ্জুরুল আলম',
                'full_name_eng' => 'MOHAMMAD MONJURUL ALAM',
                'pin' => '19786118113036060',
                'contact_no' => '01716-856830, 01913-209566', // Multiple numbers combined
                'email' => 'm_alam1978@yahoo.com, malam1978@gmail.com', // Multiple emails combined
                'designation_bng' => 'সিনিয়র জেলা নির্বাচন অফিসার',
                'designation_status' => 'full',
                'office_location' => 'সিনিয়র জেলা নির্বাচন অফিস, সিলেট (Field)',
            ],
            [
                'full_name' => 'মোঃ মুনীর হোসাইন খান',
                'full_name_eng' => 'Md. Munir Hussein Khan',
                'pin' => '19745612247875384',
                'contact_no' => '01712-017295',
                'email' => 'munir_ec2011@yahoo.com',
                'designation_bng' => 'সিনিয়র জেলা নির্বাচন অফিসার',
                'designation_status' => 'full',
                'office_location' => 'সিনিয়র জেলা নির্বাচন অফিস, পাবনা (Field)',
            ],
            [
                'full_name' => 'মো: মাহবুবুর রহমান',
                'full_name_eng' => 'Md. Mahbubur Rahman',
                'pin' => '19761022012108231',
                'contact_no' => '01715637800',
                'email' => 'kanokec@yahoo.com',
                'designation_bng' => 'সিনিয়র জেলা নির্বাচন অফিসার',
                'designation_status' => 'full',
                'office_location' => 'সিনিয়র জেলা নির্বাচন অফিস, কুষ্টিয়া (Field)',
            ],
            [
                'full_name' => 'মোঃ জাহাঙ্গীর আলম রাকিব',
                'full_name_eng' => 'MD. JAHANGIR ALAM RAKIB',
                'pin' => '19786921511581246',
                'contact_no' => '01813596893',
                'email' => 'jahangirrakib57471@gmail.com',
                'designation_bng' => 'সিনিয়র জেলা নির্বাচন অফিসার',
                'designation_status' => 'full',
                'office_location' => 'সিনিয়র জেলা নির্বাচন অফিস, যশোর (Field)',
            ],
            [
                'full_name' => 'মোহাম্মদ তাজুল ইসলাম',
                'full_name_eng' => 'MUHAMMAD TAZUL ISLAM',
                'pin' => '19756125208176843',
                'contact_no' => '01716382771',
                'email' => 'tazuldeo@gmail.com',
                'designation_bng' => 'সিনিয়র জেলা নির্বাচন অফিসার',
                'designation_status' => 'full',
                'office_location' => 'সিনিয়র জেলা নির্বাচন অফিস, টাঙ্গাইল (Field)',
            ],
            [
                'full_name' => 'গোলাম মোস্তফা',
                'full_name_eng' => 'GOLAM MOSTOFA',
                'pin' => '19779313865582880',
                'contact_no' => '01716-289167',
                'email' => 'mostofaueo@gmail.com',
                'designation_bng' => 'জেলা নির্বাচন অফিসার',
                'designation_status' => 'full',
                'office_location' => 'জেলা নির্বাচন অফিস, মৌলভীবাজার (Field)',
            ],
            [
                'full_name' => 'মোহাম্মদ নাজিম উদ্দিন',
                'full_name_eng' => 'Mohammad Nazim Uddin',
                'pin' => '19799322807540947',
                'contact_no' => '01711707733',
                'email' => 'nazimuddinueo79@gmail.com',
                'designation_bng' => 'জেলা নির্বাচন অফিসার',
                'designation_status' => 'full',
                'office_location' => 'জেলা নির্বাচন অফিস, মানিকগঞ্জ (Field)',
            ],
            [
                'full_name' => 'মোহাম্মদ জাহাঙ্গীর হোসেন',
                'full_name_eng' => 'MOHAMMAD JAHANGIR HOSSAN',
                'pin' => '19786122304702076',
                'contact_no' => '01712-189007',
                'email' => 'jahangirueo@gmail.com',
                'designation_bng' => 'জেলা নির্বাচন অফিসার',
                'designation_status' => 'full',
                'office_location' => 'জেলা নির্বাচন অফিস, শেরপুর (Field)',
            ],
            [
                'full_name' => 'মুহাম্মদ আবু আনছার',
                'full_name_eng' => 'Md. Abu Ansar',
                'pin' => '19758217375561161',
                'contact_no' => '01712784004',
                'email' => 'abuansar4235@yahoo.com',
                'designation_bng' => 'জেলা নির্বাচন অফিসার',
                'designation_status' => 'full',
                'office_location' => 'জেলা নির্বাচন অফিস, বাগেরহাট (Field)',
            ],
            [
                'full_name' => 'মোঃ আবুল হোসেন (উপ সচিব, চলতি দায়িত্ব)',
                'full_name_eng' => 'Md. Abul Hossain',
                'pin' => '19755011513155016',
                'contact_no' => '01717-817431',
                'email' => 'htt://shovon_ec@yahoo.com',
                'designation_bng' => 'জেলা নির্বাচন অফিসার',
                'designation_status' => 'full',
                'office_location' => 'জেলা নির্বাচন অফিস, ঝিনাইদহ (Field)',
            ],
            [
                'full_name' => 'মোঃ আবদুল মান্নান',
                'full_name_eng' => 'Md.Abdul Mannan',
                'pin' => '19740422809227894',
                'contact_no' => '01711051811',
                'email' => 'm_mannan_s@yahoo.com',
                'designation_bng' => 'জেলা নির্বাচন অফিসার',
                'designation_status' => 'full',
                'office_location' => 'জেলা নির্বাচন অফিস, পিরোজপুর (Field)',
            ],
            [
                'full_name' => 'মোঃ কামরুল ইসলাম',
                'full_name_eng' => 'Md. Quamrul Islam',
                'pin' => '19768524901097150',
                'contact_no' => '01712249281',
                'email' => 'quamrulueo76@gmail.com',
                'designation_bng' => 'জেলা নির্বাচন অফিসার',
                'designation_status' => 'full',
                'office_location' => 'জেলা নির্বাচন অফিস, লালমনিরহাট (Field)',
            ],
            [
                'full_name' => 'মুহাম্মদ আনোয়ারুল হক',
                'full_name_eng' => 'MOHAMMAD ANOWARUL HAQUE',
                'pin' => '19746125210181760',
                'contact_no' => '01312262020',
                'email' => 'anowarul.haque1974@gmail.com',
                'designation_bng' => 'জেলা নির্বাচন অফিসার',
                'designation_status' => 'full',
                'office_location' => 'জেলা নির্বাচন অফিস, জামালপুর (Field)',
            ],
            [
                'full_name' => 'মোহাম্মদ শহিদুল ইসলাম',
                'full_name_eng' => 'MOHAMMAD SHAHIDUL ISLAM',
                'pin' => '19789319559585380',
                'contact_no' => '01712392948',
                'email' => 'ueo.shahidul@gmail.com',
                'designation_bng' => 'জেলা নির্বাচন অফিসার',
                'designation_status' => 'full',
                'office_location' => 'জেলা নির্বাচন অফিস, গাইবান্ধা (Field)',
            ],
            [
                'full_name' => 'মোহাম্মদ জসিম উদ্দিন',
                'full_name_eng' => 'Mohammad Jashim Uddin',
                'pin' => '19761917263588311',
                'contact_no' => '01819848904, 01745769050', // Multiple numbers combined
                'email' => null,
                'designation_bng' => 'জেলা নির্বাচন অফিসার',
                'designation_status' => 'full',
                'office_location' => 'জেলা নির্বাচন অফিস, মুন্সীগঞ্জ (Field)',
            ],
            [
                'full_name' => 'মোহাম্মদ জাহিদ হোসেন',
                'full_name_eng' => 'MOHAMMAD ZAHID HOSSAIN',
                'pin' => '19742924705140577',
                'contact_no' => '01716851825',
                'email' => null,
                'designation_bng' => 'জেলা নির্বাচন অফিসার',
                'designation_status' => 'full',
                'office_location' => 'জেলা নির্বাচন অফিস, ঝালকাঠী (Field)',
            ],
            [
                'full_name' => 'মোহাম্মদ মোরশেদ আলম',
                'full_name_eng' => 'Mohammad Morshed Alam',
                'pin' => '19786816315187907',
                'contact_no' => '01718724809',
                'email' => 'morshedkhanepur@gmail.com',
                'designation_bng' => 'জেলা নির্বাচন অফিসার',
                'designation_status' => 'full',
                'office_location' => 'জেলা নির্বাচন অফিস, কিশোরগঞ্জ (Field)',
            ],
            [
                'full_name' => 'মোহাম্মদ শাহীন আকন্দ',
                'full_name_eng' => 'Mohammad Shahin Akond',
                'pin' => '19782619351956212',
                'contact_no' => '01914198505',
                'email' => 'shahin307zh@yahoo.com',
                'designation_bng' => 'জেলা নির্বাচন অফিসার',
                'designation_status' => 'full',
                'office_location' => 'জেলা নির্বাচন অফিস, নরসিংদী (Field)',
            ],
            [
                'full_name' => 'মোহাম্মদ শানিয়াজ্জামান তালুকদার',
                'full_name_eng' => 'Mohammad Shaniazzaman Talukder',
                'pin' => '19757218355215452',
                'contact_no' => '01716943933',
                'email' => 'Shaniazzaman@yahoo.com',
                'designation_bng' => 'জেলা নির্বাচন অফিসার',
                'designation_status' => 'full',
                'office_location' => 'জেলা নির্বাচন অফিস, ব্রাক্ষ্মণবাড়িয়া (Field)',
            ],
            [
                'full_name' => 'মোঃ আঃ আজিজ',
                'full_name_eng' => 'Md. Abdul Aziz',
                'pin' => '19770125804330040',
                'contact_no' => '01711129969',
                'email' => 'maazizec@gmail.com',
                'designation_bng' => 'জেলা নির্বাচন অফিসার',
                'designation_status' => 'full',
                'office_location' => 'জেলা নির্বাচন অফিস, কক্সবাজার (Field)',
            ],
            [
                'full_name' => 'মোঃ লুৎফুল কবীর সরকার',
                'full_name_eng' => 'Md. Lutful Kobir Sarkar',
                'pin' => '19783218885280227',
                'contact_no' => '01711061503',
                'email' => 'lutful_kobir.yahoo.com',
                'designation_bng' => 'জেলা নির্বাচন অফিসার',
                'designation_status' => 'full',
                'office_location' => 'জেলা নির্বাচন অফিস, নীলফামারী (Field)',
            ],
            // Rows 41 to 843 are truncated in the provided data, so they are omitted here. You would need to add them manually from the full Excel file.
            // Continuing from row 844 as per the provided data...
            [
                'full_name' => 'জাকির মাহ্‌মুদ',
                'full_name_eng' => 'Jakir Mahmud',
                'pin' => '19854820604420551',
                'contact_no' => '01718564635',
                'email' => 'j.mahmud32@gmail.com',
                'designation_bng' => 'সহকারী পরিচালক',
                'designation_status' => 'full',
                'office_location' => 'মুদ্রন ও বিতরণ (এনআইডি)',
            ],
            [
                'full_name' => 'মিসবাহ উদ্দীন আহমেদ',
                'full_name_eng' => 'Misbah Uddin Ahmed',
                'pin' => '19836112047336697',
                'contact_no' => '01717-244078',
                'email' => 'muahmedah@gmail.com',
                'designation_bng' => 'সহকারী পরিচালক',
                'designation_status' => 'full',
                'office_location' => 'সংশোধন ও প্রতিস্থাপন (এনআইডি)',
            ],
            [
                'full_name' => 'আবুল কাশেম মোহাম্মদ মাজহারুল ইসলাম',
                'full_name_eng' => 'ABUL KASHEM MOHAMMED MAZHARUL ISLAM',
                'pin' => '19746122205140160',
                'contact_no' => '01712463483',
                'email' => 'akmislam74@gmail.com',
                'designation_bng' => 'উপ-পরিচালক',
                'designation_status' => 'full',
                'office_location' => 'জাতীয় পরিচয়পত্র সেবা (এনআইডি)',
            ],
            [
                'full_name' => 'মুহাঃ সরওয়ার হোসেন',
                'full_name_eng' => 'Muhammad Sarwar Hossain',
                'pin' => '19805027901100984',
                'contact_no' => '01717-405594',
                'email' => 'sarwarueo@gmail.com',
                'designation_bng' => 'সহকারী পরিচালক',
                'designation_status' => 'full',
                'office_location' => 'সঠিকতা যাচাইকরণ (এনআইডি)',
            ],
            [
                'full_name' => 'মো: ইকরামুল হাসান',
                'full_name_eng' => 'Md. Ikramul Hasan',
                'pin' => '19846125213197544',
                'contact_no' => '01797185123',
                'email' => 'mihasankth@gmail.com',
                'designation_bng' => 'সহকারী পরিচালক',
                'designation_status' => 'full',
                'office_location' => 'তথ্য অনুসন্ধান (এনআইডি)',
            ],
            [
                'full_name' => 'মুহাম্মদ আশরাফ হোসেন',
                'full_name_eng' => 'Mohammad Ashraf Hussain',
                'pin' => '19732612935354367',
                'contact_no' => '01911-390029',
                'email' => 'ahrdp06@yahoo.com',
                'designation_bng' => 'সিস্টেম ম্যানেজার',
                'designation_status' => 'full',
                'office_location' => 'কারিগরী (এনআইডি)',
            ],
            [
                'full_name' => 'আক্তারুজ্জামান',
                'full_name_eng' => 'AKHTARUZZAMAN',
                'pin' => '19802690243808585',
                'contact_no' => '01550167290',
                'email' => 'akhtar@ecs.gov.bd',
                'designation_bng' => 'সিস্টেম এনালিস্ট',
                'designation_status' => 'full',
                'office_location' => 'উপাত্ত ব্যবস্থাপনা শাখা (এনআইডি)',
            ],
            [
                'full_name' => 'সিফাত জাহান',
                'full_name_eng' => 'Shifat Jahan',
                'pin' => '19859116290493415',
                'contact_no' => '01911614098',
                'email' => 'shifat_ruma@yahoo.com',
                'designation_bng' => 'প্রোগ্রামার',
                'designation_status' => 'full',
                'office_location' => 'উপাত্ত ব্যবস্থাপনা শাখা (এনআইডি)',
            ],
            [
                'full_name' => 'মোহাম্মদ আসাদুজ্জামান',
                'full_name_eng' => 'Mohammad Asaduzzaman',
                'pin' => '19712695041734096',
                'contact_no' => '01941456850',
                'email' => 'asadit2010@gmail.com',
                'designation_bng' => 'সহকারী প্রোগ্রামার',
                'designation_status' => 'full',
                'office_location' => 'উপাত্ত ব্যবস্থাপনা শাখা (এনআইডি)',
            ],
            [
                'full_name' => 'প্রকৌশলী মোহাম্মদ আরিফুল ইসলাম',
                'full_name_eng' => 'Engr. Mohammad Ariful Islam',
                'pin' => '19824810694319934',
                'contact_no' => '01551061583',
                'email' => 'arifecs@gmail.com',
                'designation_bng' => 'সিস্টেম এনালিস্ট',
                'designation_status' => 'full',
                'office_location' => 'আই এস শাখা (এনআইডি)',
            ],
            [
                'full_name' => 'মোঃ সেলিম উল আলম',
                'full_name_eng' => 'Md. Salim Ul Alam',
                'pin' => '19875017982372860',
                'contact_no' => '01725991337',
                'email' => 'salimbabu55@gmail.com',
                'designation_bng' => 'প্রোগ্রামার',
                'designation_status' => 'full',
                'office_location' => 'আই এস শাখা (এনআইডি)',
            ],
            [
                'full_name' => 'আমিনুল ইসলাম',
                'full_name_eng' => 'Aminul Islam',
                'pin' => '19886515279000022',
                'contact_no' => '01727902023',
                'email' => null,
                'designation_bng' => 'প্রোগ্রামার',
                'designation_status' => 'full',
                'office_location' => 'আই এস শাখা- (এনআইডি)',
            ],
            [
                'full_name' => 'মোহাম্মদ সোহাগ',
                'full_name_eng' => 'Mohammed Shohag',
                'pin' => '19872696829753917',
                'contact_no' => '01551803454',
                'email' => 'md.shohag_ecs@yahoo.com',
                'designation_bng' => 'মেনটেইনেন্স ইঞ্জিনিয়ার',
                'designation_status' => 'full',
                'office_location' => 'আইসিটি পরিচালনা (এনআইডি)',
            ],
            [
                'full_name' => 'মোহাম্মাদ হাবিবুর রহমান',
                'full_name_eng' => 'Mohammad Habibur Rahman',
                'pin' => '19805617019093353',
                'contact_no' => '01717955200',
                'email' => 'habib_rosy@yahoo.com',
                'designation_bng' => 'পরিচালক',
                'designation_status' => 'full',
                'office_location' => 'প্রশাসন ও অর্থ (এনআইডি)',
            ],
            [
                'full_name' => 'কাজী মোঃ ইস্তাফিজুল হক আকন্দ',
                'full_name_eng' => 'Kazi MD Istafizul Haque Akand',
                'pin' => '19752627206576032',
                'contact_no' => '01711-017313',
                'email' => 'istafizulbabu@gmail.com',
                'designation_bng' => 'পরিচালক',
                'designation_status' => 'cc',
                'office_location' => 'বাজেট, হিসাব ও সাধারণ সেবা (এনআইডি)',
            ],
            [
                'full_name' => 'মোসাঃ মাহাফুজা আক্তার',
                'full_name_eng' => 'Mosa. Mahafuza Akter',
                'pin' => '19762698875745442',
                'contact_no' => '0171-6244393',
                'email' => 'mahafuza.1976@gmail.com',
                'designation_bng' => 'উপ-পরিচালক',
                'designation_status' => 'full',
                'office_location' => 'তথ্য যাচাই সেবা (এনআইডি)',
            ],
            [
                'full_name' => 'মোঃ শুভ আল হোসাইন',
                'full_name_eng' => 'Md. Shuvo Al Hossain',
                'pin' => '19968198507000049',
                'contact_no' => '01717-884473',
                'email' => 'shuvo.cse.95@gmail.com',
                'designation_bng' => 'সহকারী পরিচালক',
                'designation_status' => 'full',
                'office_location' => 'যানবাহন, ষ্টোর ও সাধারণ সেবা (এনআইডি)',
            ],
            [
                'full_name' => 'দেয়ালী পাল',
                'full_name_eng' => 'Dewali Paul',
                'pin' => '19856125221271975',
                'contact_no' => '01729516130',
                'email' => 'dewalibec@gmail.com',
                'designation_bng' => 'সহকারী পরিচালক',
                'designation_status' => 'full',
                'office_location' => 'বাজেট (এনআইডি)',
            ],
            [
                'full_name' => 'মোহাম্মদ তোফায়েল হোসেন',
                'full_name_eng' => 'Mohammad Tofaul Hossain',
                'pin' => '19806111636349938',
                'contact_no' => '01915529906',
                'email' => 'Tofaelueo80@gmail.com',
                'designation_bng' => 'উপ-পরিচালক',
                'designation_status' => 'full',
                'office_location' => 'মানবসম্পদ গবেষনা ও উন্নয়ন (এনআইডি)',
            ],
            [
                'full_name' => 'হাবিবা আখতার',
                'full_name_eng' => 'HABIBA AKHTAR',
                'pin' => '19836126509834883',
                'contact_no' => '01953593510',
                'email' => 'habibaec@gmail.com',
                'designation_bng' => 'সহকারী পরিচালক',
                'designation_status' => 'full',
                'office_location' => 'মানবসম্পদ ও প্রশিক্ষণ (এনআইডি)',
            ],
            [
                'full_name' => 'মাহবুবা মমতা হেনা',
                'full_name_eng' => 'Mahbuba Momta Hena',
                'pin' => '19786121304606003',
                'contact_no' => '01558350124',
                'email' => 'mahbubahena@gmail.com',
                'designation_bng' => 'উপ-পরিচালক',
                'designation_status' => 'full',
                'office_location' => 'গবেষণা ও উন্নয়ন (এনআইডি)',
            ],
            [
                'full_name' => 'খান আবি শাহানুর খান',
                'full_name_eng' => 'KHAN ABI SHAHANUR KHAN',
                'pin' => '19780695119234899',
                'contact_no' => '01720554218',
                'email' => 'kaskhan.deo@gmail.com',
                'designation_bng' => 'পরিচালক',
                'designation_status' => 'full',
                'office_location' => 'নিবন্ধন ও প্রবাসী অধিশাখা (এনআইডি)',
            ],
            [
                'full_name' => 'সালাহউদ্দীন আহমদ',
                'full_name_eng' => 'Salahuddin Ahmad',
                'pin' => '19765027905126840',
                'contact_no' => '01712591144',
                'email' => 'salahuddin.ecs.15@gmail.com',
                'designation_bng' => 'পরিচালক',
                'designation_status' => 'cc',
                'office_location' => '(পদায়নকৃত পদ ও শাখা) উপ-পরিচালক, (নিবন্ধন ও প্রবাসী সেবা শাখা) (এনআইডি)',
            ],
            [
                'full_name' => 'মোঃ ফরহাদ হোসেন',
                'full_name_eng' => 'Md. Forhad Hossain',
                'pin' => '19683624409000002',
                'contact_no' => '01817-675173',
                'email' => 'forhadhossain_ecs@yahoo.com',
                'designation_bng' => 'পরিচালক',
                'designation_status' => 'full',
                'office_location' => 'জাতীয় পরিচয় নিবন্ধন অনুবিভাগ (এনআইডি)',
            ],
            [
                'full_name' => 'মোছাঃ সিরাজুম মনিরা চৌধুরী',
                'full_name_eng' => 'Mst Serajum Monira Chowdhury',
                'pin' => '19793816147642798',
                'contact_no' => '01717017189',
                'email' => 'smonira3@gmail.com',
                'designation_bng' => 'নির্বাচন কর্মকর্তা',
                'designation_status' => 'full',
                'office_location' => 'জাতীয় পরিচয় নিবন্ধন অনুবিভাগ(সংযুক্ত) (এনআইডি)',
            ],
            [
                'full_name' => 'মুহাম্মদ হাসানুজ্জামান',
                'full_name_eng' => 'MOHAMMAD HASANUZZAMAN',
                'pin' => '19770922501247995',
                'contact_no' => '01711387783',
                'email' => 'hasanuzzaman_kabir@yahoo.com.',
                'designation_bng' => 'মহাপরিচালক',
                'designation_status' => 'acting',
                'office_location' => 'মহাপরিচালকের দপ্তর (নিপ্রই)',
            ],
            [
                'full_name' => 'মোঃ আতিয়ার রহমান',
                'full_name_eng' => 'Md. Atiar Rahman',
                'pin' => '19748123107583385',
                'contact_no' => '01716-846982',
                'email' => 'atiar.geo@gmail.com',
                'designation_bng' => 'পরিচালক',
                'designation_status' => 'full',
                'office_location' => 'প্রশিক্ষণ, নির্বাচনি প্রশিক্ষণ ইনস্টিটিউট (নিপ্রই)',
            ],
            [
                'full_name' => 'মোহাম্মদ জাহাঙ্গীর আলম',
                'full_name_eng' => 'Mohammad Jahangir Alam',
                'pin' => '19776527603103673',
                'contact_no' => '01714129771',
                'email' => 'j_alam777@yahoo.com',
                'designation_bng' => 'উপ-পরিচালক',
                'designation_status' => 'full',
                'office_location' => 'স্থানীয় (নিপ্রই)',
            ],
            [
                'full_name' => 'আয়েশা আক্তার (উপ পরিচালক , চলতি দায়িত্ব)',
                'full_name_eng' => 'AYESHA AKTER',
                'pin' => '19788826706597710',
                'contact_no' => '01918265845',
                'email' => null,
                'designation_bng' => 'সহকারী পরিচালক',
                'designation_status' => 'full',
                'office_location' => 'প্রশিক্ষণ-২ (নিপ্রই)',
            ],
            [
                'full_name' => 'মোঃ রিয়াজ উদ্দিন',
                'full_name_eng' => 'Md. Riaz Uddin',
                'pin' => '19852612935354089',
                'contact_no' => '01711931704',
                'email' => 'riaz1919@yahoo.com',
                'designation_bng' => 'সহকারী পরিচালক',
                'designation_status' => 'full',
                'office_location' => 'প্রশিক্ষণ-১ (নিপ্রই)',
            ],
            [
                'full_name' => 'মোহাম্মদ নুরুল আলম',
                'full_name_eng' => 'MOHAMMAD NURUL ALAM',
                'pin' => '19741592828036865',
                'contact_no' => '01824715756',
                'email' => 'n_alam13@yahoo.com',
                'designation_bng' => 'পরিচালক',
                'designation_status' => 'cc',
                'office_location' => 'প্রশাসন (নিপ্রই)',
            ],
            [
                'full_name' => 'মোঃতকদির আহমেদ',
                'full_name_eng' => 'Md. Takdir Ahmed',
                'pin' => '19782694259582059',
                'contact_no' => '01711185200',
                'email' => 'takdirahmed.ec@gmail.com',
                'designation_bng' => 'উপ-পরিচালক',
                'designation_status' => 'full',
                'office_location' => 'উপপরিচালক (আন্তর্জাতিক) (নিপ্রই)',
            ],
            [
                'full_name' => 'মোঃ আরিফুল হক',
                'full_name_eng' => 'Md. Ariful Haque',
                'pin' => '19744124709121036',
                'contact_no' => '01911923596',
                'email' => 'mdarifulhaque385@gmail.com',
                'designation_bng' => 'উপ-পরিচালক',
                'designation_status' => 'full',
                'office_location' => 'প্রশাসন_ (নিপ্রই)',
            ],
            [
                'full_name' => 'ফৌজিয়া সিদ্দিক',
                'full_name_eng' => 'Fawzia Siddique',
                'pin' => '19852619551891342',
                'contact_no' => '01716587812',
                'email' => 'fawziasiddique@gmail.com',
                'designation_bng' => 'সহকারী পরিচালক',
                'designation_status' => 'full',
                'office_location' => 'সহকারী পরিচালক (আন্তর্জাতিক) (নিপ্রই)',
            ],
            [
                'full_name' => 'ফারজানা রহমান',
                'full_name_eng' => 'Farzana Rahman',
                'pin' => '19872692619467680',
                'contact_no' => '01911319501',
                'email' => null,
                'designation_bng' => 'সহকারী পরিচালক',
                'designation_status' => 'full',
                'office_location' => 'লজিষ্টিক সাপোর্ট (নিপ্রই)',
            ],
            [
                'full_name' => 'মোহাম্মদ নুরুল হাসান ভূঞা',
                'full_name_eng' => 'Mohammad Nurul Hasan Bhuiyan',
                'pin' => '19764624905248230',
                'contact_no' => '01711369976',
                'email' => 'deocckc@gmail.com',
                'designation_bng' => 'উপ-পরিচালক',
                'designation_status' => 'full',
                'office_location' => 'গবেষণা ও ডকুমেন্টেশন (নিপ্রই)',
            ],
            [
                'full_name' => 'আকতার জাহান',
                'full_name_eng' => 'Akter Jahan',
                'pin' => '19712694807845974',
                'contact_no' => '01911953028',
                'email' => 'jahan_simul@yahoo.com',
                'designation_bng' => 'সহকারী পরিচালক',
                'designation_status' => 'full',
                'office_location' => 'লাইব্রেরী, গবেষনা ও ডকুমেন্টেশন (নিপ্রই)',
            ],
            [
                'full_name' => 'মো: আলা উদ্দিন আল মামুন (পরিচালক, চলতি দায়িত্ব)',
                'full_name_eng' => 'MD. ALA UDDIN AL MAMUN',
                'pin' => '19767520701463914',
                'contact_no' => '01711204685',
                'email' => 'alauddin_almamun@yahoo.com',
                'designation_bng' => 'উপ-পরিচালক',
                'designation_status' => 'full',
                'office_location' => 'উপ-পরিচালক (জাতীয়) (নিপ্রই)',
            ],
            [
                'full_name' => 'আজিমুল ইসলাম',
                'full_name_eng' => 'Azimul Islam',
                'pin' => '19862215683244848',
                'contact_no' => '01816278417',
                'email' => 'shuhagcse@gmail.com',
                'designation_bng' => 'প্রোগ্রামার',
                'designation_status' => 'full',
                'office_location' => 'আইসিটি (নিপ্রই)',
            ],
            [
                'full_name' => 'শুধাংশু কুমার সরকার',
                'full_name_eng' => 'Sudangsu kumar Sarkar',
                'pin' => '19662695045917245',
                'contact_no' => '01711736611',
                'email' => null,
                'designation_bng' => 'সহকারী প্রোগ্রামার',
                'designation_status' => 'full',
                'office_location' => 'আইসিটি (নিপ্রই)',
            ],
            [
                'full_name' => 'তানজিদা আফরিন ছন্দা',
                'full_name_eng' => 'Tanjida Afrin Chhanda',
                'pin' => '19886826011000062',
                'contact_no' => '01737039035',
                'email' => 'chhanda2007@gmail.com',
                'designation_bng' => 'সহকারী পরিচালক',
                'designation_status' => 'full',
                'office_location' => 'সহকারী পরিচালক (প্রশিক্ষণ-৩) (নিপ্রই)',
            ],
            [
                'full_name' => 'মোঃ হেলাল উদ্দিন খান',
                'full_name_eng' => 'Md. Helal Uddin khan',
                'pin' => '19747815794478639',
                'contact_no' => '01712582710',
                'email' => 'helal.ecsoff.bd@gmail.com',
                'designation_bng' => 'উপসচিব(সংযুক্ত)',
                'designation_status' => 'full',
                'office_location' => 'নির্বাচনি প্রশিক্ষণ ইন্সটিটিউট (নিপ্রই)',
            ],
            [
                'full_name' => 'মো: মোশাররফ হোসেন',
                'full_name_eng' => 'Md. Musharraf Hossain',
                'pin' => '19662691651198642',
                'contact_no' => '01771187700',
                'email' => null,
                'designation_bng' => 'সহকারী পরিচালক',
                'designation_status' => 'full',
                'office_location' => 'নির্বাচনি প্রশিক্ষণ ইন্সটিটিউট (নিপ্রই)',
            ],
            [
                'full_name' => 'মমতাজ বেগম',
                'full_name_eng' => 'Momataj Begum',
                'pin' => '19692695433104576',
                'contact_no' => '01726024618',
                'email' => null,
                'designation_bng' => 'সহকারী পরিচালক',
                'designation_status' => 'full',
                'office_location' => 'নির্বাচনি প্রশিক্ষণ ইন্সটিটিউট (নিপ্রই)',
            ],
            [
                'full_name' => 'সৈয়দা সাদিকা সুলতানা',
                'full_name_eng' => 'Syeda Sadika Sultana',
                'pin' => '19781593525449837',
                'contact_no' => '01817763197',
                'email' => 'SyedaSadika@yahoo.com',
                'designation_bng' => 'সহকারী পরিচালক',
                'designation_status' => 'full',
                'office_location' => 'নির্বাচনি প্রশিক্ষণ ইন্সটিটিউট (নিপ্রই)',
            ],
            [
                'full_name' => 'মোছা: খায়রুন নাহার',
                'full_name_eng' => 'Most. Khairun Nahar',
                'pin' => '19876125221272157',
                'contact_no' => '01737-122768',
                'email' => 'sheuly_bau@ymail.com',
                'designation_bng' => 'সহকারী পরিচালক',
                'designation_status' => 'full',
                'office_location' => 'নির্বাচনি প্রশিক্ষণ ইন্সটিটিউট (নিপ্রই)',
            ],
            [
                'full_name' => 'তাছলিমা আক্তার',
                'full_name_eng' => 'TASLIMA AKTER',
                'pin' => '19802693004981171',
                'contact_no' => '01716-546825',
                'email' => null,
                'designation_bng' => 'সহকারী পরিচালক',
                'designation_status' => 'full',
                'office_location' => 'নির্বাচনি প্রশিক্ষণ ইন্সটিটিউট (নিপ্রই)',
            ],
        ];

        foreach ($voters as $voter) {
            Voter::create($voter);
        }
    }
}